WHY_CPP: Drawing
Drawing
WHYCPP Public API
Functions to draw something on the screen.
Classes
struct RGBA
Functions
int GetDisplayWidth (const Context &context)
int GetDisplayHeight (const Context &context)
void SetPixel (Context &context, int x, int y, const RGBA &color)
const RGBA GetPixel (const Context &context, int x, int y)
void DrawClearScreen (Context &context, const RGBA &color={0, 0, 0, 255})
void DrawLine (Context &context, int x0, int y0, int x1, int y1, const RGBA &color)
void DrawRectFill (Context &context, int x, int y, int w, int h, const RGBA &color)
void DrawRect (Context &context, int x, int y, int w, int h, const RGBA &color)
void DrawCircle (Context &context, int x, int y, int radius, const RGBA &color)
void DrawCircleFill (Context &context, int x, int y, int radius, const RGBA &color)
void DrawSprite (Context &context, int sprite_id, int screen_x, int screen_y, int sheet_x, int sheet_y, int width, int height)
Detailed Description
Functions to draw something on the screen.
Function Documentation
void DrawCircle (Context & context, int x, int y, int radius, const RGBA & color)
Draw a circle border with the color. Circle body is transparent
Parameters
context
x coordinate of the circle's center
y coordinate of the circle's center
radius
color
See Also
DrawCircleFill()
Definition at line 61 of file drawing.cpp.
References SetPixel().
void DrawCircleFill (Context & context, int x, int y, int radius, const RGBA & color)
Draw a circle border with the color. Circle body is filled with the same color as the border.
Parameters
context
x coordinate of the circle's center
y coordinate of the circle's center
radius
color
See Also
DrawCircle()
Definition at line 77 of file drawing.cpp.
References SetPixel().
void DrawClearScreen (Context & context, const RGBA & color = {0, 0, 0, 255})
Fill the screen with a solid color
Parameters
context
color to fill the screen
Definition at line 22 of file drawing.cpp.
References GetDisplayHeight(), GetDisplayWidth(), and SetPixel().
void DrawLine (Context & context, int x0, int y0, int x1, int y1, const RGBA & color)
Draw line on the screen from the [x0,y0] to the [x1,y1] with a color.
Parameters
context
x0 coordinate of the first point
y0 coordinate of the first point
x1 coordinate of the second point
y1 coordinate of the second point
color of the line
Definition at line 29 of file drawing.cpp.
References SetPixel().
Referenced by DrawRect(), and DrawRectFill().
void DrawRect (Context & context, int x, int y, int w, int h, const RGBA & color)
Draw a rectangle borders with the color. Rectangle body is transparent.
To draw it you need a left-upper corner coordinates [x,y] and rectangle width and height.
Parameters
context
x coordinate of the left-upper corner
y coordinate of the left-upper corner
w width of the rectangle to draw
h width of the rectangle to draw
color of the borders and filler
See Also
DrawRectFill()
Definition at line 54 of file drawing.cpp.
References DrawLine().
void DrawRectFill (Context & context, int x, int y, int w, int h, const RGBA & color)
Draw a rectangle and fill it with color. To draw it you need a left-upper corner coordinates [x,y] and rectangle width and height.
Parameters
context
x coordinate of the left-upper corner
y coordinate of the left-upper corner
w width of the rectangle to draw
h width of the rectangle to draw
color of the borders and filler
See Also
DrawRect()
Definition at line 49 of file drawing.cpp.
References DrawLine().
int GetDisplayHeight (const Context & context)
Parameters
context
Returns
display height in pixels
Definition at line 11 of file drawing.cpp.
Referenced by DrawClearScreen().
int GetDisplayWidth (const Context & context)
Parameters
context
Returns
display width in pixels
Definition at line 8 of file drawing.cpp.
Referenced by DrawClearScreen().
const RGBA GetPixel (const Context & context, int x, int y)
Get the pixel color at the [x,y] position
Parameters
context of the application
x coordinate of the pixel on the screen
y coordinate of the pixel on the screen
Returns
color of the pixel
Definition at line 19 of file drawing.cpp.
void SetPixel (Context & context, int x, int y, const RGBA & color)
Set the pixel color at the [x,y] position
Parameters
context of the application
x coordinate of the pixel on the screen
y coordinate of the pixel on the screen
color of the pixel
Definition at line 14 of file drawing.cpp.
Referenced by DrawCircle(), DrawCircleFill(), DrawClearScreen(), DrawLine(), and Print().